### ISSUE TITLE
Why does it exist?

### ISSUE THREAD

**Issue by ooovlad** [meyskens/mastodon-for-workgroups#3]
Hello, @meyskens!

I am sorry to disturb you but I have one question that can't leave my mind. Could you please gently explain me why does this software exist? What is the purpose of it? I am really curious of your motivation to create this.

_Thanks for your answer._

**Comment by meyskens** [comment]
Honest answer: I was bored in my day job at the time and needed a challenge so I decided to learn VB6 a language/framework where you barely find information about online, all your Chat AI tools are useless at it and the best resources is a CD and Archive.org books. This combined with a passion for retro computing I made this al on an actual early 90s PC. 

Probably the same motivations behind many of the retro apps on https://joinmastodon.org/apps. Sadly I wish i had the time to continue developing this program further :(
